// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSbJRmIoWIHXrSQ9Fb0J5g7bWKjv3Jmk0',
    appId: '1:245872188063:web:57cfff1ebf64ac4dc120aa',
    messagingSenderId: '245872188063',
    projectId: 'firestoretestingapp-f6fa1',
    authDomain: 'firestoretestingapp-f6fa1.firebaseapp.com',
    databaseURL: 'https://firestoretestingapp-f6fa1-default-rtdb.firebaseio.com',
    storageBucket: 'firestoretestingapp-f6fa1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlJRw3e5e-ho2bdavU1vpOEVqadlQvOJw',
    appId: '1:245872188063:android:b5c610bfb2049e9dc120aa',
    messagingSenderId: '245872188063',
    projectId: 'firestoretestingapp-f6fa1',
    databaseURL: 'https://firestoretestingapp-f6fa1-default-rtdb.firebaseio.com',
    storageBucket: 'firestoretestingapp-f6fa1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL19xsSprNsylDXmo9eQaFV_uOA5jDbTU',
    appId: '1:245872188063:ios:8c91d85f024f7e49c120aa',
    messagingSenderId: '245872188063',
    projectId: 'firestoretestingapp-f6fa1',
    databaseURL: 'https://firestoretestingapp-f6fa1-default-rtdb.firebaseio.com',
    storageBucket: 'firestoretestingapp-f6fa1.appspot.com',
    iosClientId: '245872188063-faseeintpea65ghfcjjgcln25inqg5bm.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireStoreTestingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL19xsSprNsylDXmo9eQaFV_uOA5jDbTU',
    appId: '1:245872188063:ios:8c91d85f024f7e49c120aa',
    messagingSenderId: '245872188063',
    projectId: 'firestoretestingapp-f6fa1',
    databaseURL: 'https://firestoretestingapp-f6fa1-default-rtdb.firebaseio.com',
    storageBucket: 'firestoretestingapp-f6fa1.appspot.com',
    iosClientId: '245872188063-faseeintpea65ghfcjjgcln25inqg5bm.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireStoreTestingApp',
  );
}
